import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        
         <Navbar/>
    <main className="place-content-center h-screen">
      {children}
    </main>
    {/* footer */}
    <footer className="bg-gray-100 text-center text-gray-700 py-6 mt-12 shadow-inner">
      <div className="max-w-6xl mx-auto px-4">
        <p className="text-sm md:text-base">
          &copy; {new Date().getFullYear()} Fakrul Hossain | All rights reserved.
        </p>
        <div className="mt-2 space-x-4 text-sm">
          <a href="mailto:dev.fakrulhossain@gmail.com" className="hover:text-indigo-600 transition">
            Email
          </a>
          <a href="https://github.com/fakrul-hossain" target="_blank" rel="noopener noreferrer" className="hover:text-indigo-600 transition">
            GitHub
          </a>
          <a href="https://www.linkedin.com/fakrul-hossain/" target="_blank" rel="noopener noreferrer" className="hover:text-indigo-600 transition">
            LinkedIn
          </a>
        </div>
      </div>
    </footer>
      </body>
    </html>
  );
}
